---
title: "Tab_Enrollment_Summary_Dash_Info"
author: "Joy Baule"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tableau Enrollment Summary Dashboard ##

The Student Enrollment Summary dashboard was created and published in Tableau. It lives on the viz.uen.org Tableau Server. This dashboard is scheduled for extract refresh Mon-Fri at 4 a.m.

Link to dashboard on the viz.uen.org server: https://viz.uen.org/t/dixie/views/Studentenrollmentsummary/Studentenrollment?%3AshowAppBanner=false&%3Adisplay_count=n&%3AshowVizHome=n&%3Aorigin=viz_share_link&%3AisGuestRedirectFromVizportal=y&%3Aembed=y#3

A copy of this dashboard can be downloaded from viz.uen.org for updates. Credentials for viz.uen.org need to be assigned for use.

PostgreSQL for this dashboard was written on the Edify/EAB data warehouse.

The dashboard is organized into four tabs: 

* Overview
* Demographics 
* Residency
* Programs

# Filters on this dashboard #

* Term > Fall 2015
* College Student Level (Graduate, Undergraduate, Non-Credit)
* Concurrent Students (Include and Exclude population) 
* Ethnicity 
* Student Athlete status 
* Veteran status 
* Prior Term Data comparison (Example: Fall 22 to Fall 21)

# Overview Tab Vizualizations #

* Historical enrollment by Fall, Spring, and Summer
* Enrollment by college 
* Enrollment by entry action

# Demographics Vizualizations #

* Current selected term headcount
* Age
* First Generation
* Race/Ethnicity 
* Enrollment by college

# Residency Vizualizations # 

* Residency: In State, Out of State, International
* Enrollment by Utah county
* Enrollment by State

# Programs Vizualizations #

* Majors by College